name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # Step 4: Run Jest tests for the server
      - name: Run server tests (Jest)
        working-directory: ./server
        run: npm test -- --ci --coverage

      # Step 5: Install client dependencies
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      # Step 6: Install Playwright browsers
      - name: Install Playwright browsers
        working-directory: ./client
        run: npx playwright install

      # # Step 7: Start backend server
      # - name: Start backend server
      #   working-directory: ./server
      #   run: npm start &
      #   env:
      #     PORT: 5000

      # # Step 8: Start frontend server
      # - name: Start frontend server
      #   working-directory: ./client
      #   run: npm start &
      #   env:
      #     REACT_APP_API_URL: http://localhost:5000

      # # Step 9: Wait for frontend to be ready
      # - name: Wait for frontend to be ready
      #   run: npx wait-on http://localhost:3000 --timeout 30000

      # Step 8: Build and Serve Frontend
      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Serve client
        run: npx serve -s client/build &


      # Step 10: Run Playwright tests for the client
      - name: Run client tests (Playwright)
        working-directory: ./client
        run: npx playwright test
        env:
          CI: true

      # Step 11: Upload Jest coverage report
      - name: Upload Jest coverage
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: ./server/coverage

      # Step 12: Upload Playwright artifacts
      - name: Upload Playwright artifacts
        if: failure() # Only upload on failure
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: test-results
